---
name: Tree-Simple
version: 1.15
author:
  - 'stevan little, E<lt>stevan@iinteractive.comE<gt>'
abstract: A simple tree object
license: perl
requires:
  Scalar::Util: 1.10
  perl: 5.6.0
build_requires:
  Test::Exception: 0.15
  Test::More: 0.47
provides:
  Tree::Simple:
    file: lib/Tree/Simple.pm
    version: 1.15
  Tree::Simple::Visitor:
    file: lib/Tree/Simple/Visitor.pm
    version: 1.11
generated_by: Module::Build version 0.2701
